name: trpc_generator
description: A TRPC router mapper for Dart.
version: 0.1.0
repository: https://github.com/wosherco/trpc-client-dart
issue_tracker: https://github.com/wosherco/trpc-client-dart/issues
homepage: https://github.com/wosherco/trpc-client-dart

environment:
  sdk: ^3.4.0

dependencies:
  trpc_client: ^0.3.4

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:
