# Created with package:mono_repo v6.6.2
name: Dart CI
on:
  push:
    branches:
      - main
      - master
  pull_request:
defaults:
  run:
    shell: bash
env:
  PUB_ENVIRONMENT: bot.github
permissions: read-all

jobs:
  job_001:
    name: "analyze_format; linux; Dart 3.4.0; PKG: trpc_client; `dart analyze`"
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;sdk:3.4.0;packages:trpc_client;commands:analyze_1"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted;sdk:3.4.0;packages:trpc_client
            os:ubuntu-latest;pub-cache-hosted;sdk:3.4.0
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@0a8a0fc875eb934c15d08629302413c671d3f672
        with:
          sdk: "3.4.0"
      - id: checkout
        name: Checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
      - id: trpc_client_pub_upgrade
        name: trpc_client; dart pub upgrade
        run: dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: trpc_client
      - name: trpc_client; dart analyze
        run: dart analyze
        if: "always() && steps.trpc_client_pub_upgrade.conclusion == 'success'"
        working-directory: trpc_client
  job_002:
    name: "analyze_format; linux; Dart 3.4.0; PKG: trpc_generator; `dart analyze`"
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;sdk:3.4.0;packages:trpc_generator;commands:analyze_1"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted;sdk:3.4.0;packages:trpc_generator
            os:ubuntu-latest;pub-cache-hosted;sdk:3.4.0
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@0a8a0fc875eb934c15d08629302413c671d3f672
        with:
          sdk: "3.4.0"
      - id: checkout
        name: Checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
      - id: trpc_generator_pub_upgrade
        name: trpc_generator; dart pub upgrade
        run: dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: trpc_generator
      - name: trpc_generator; dart analyze
        run: dart analyze
        if: "always() && steps.trpc_generator_pub_upgrade.conclusion == 'success'"
        working-directory: trpc_generator
  job_003:
    name: "analyze_format; linux; Dart dev; PKG: trpc_client; `dart format --output=none --set-exit-if-changed .`, `dart analyze --fatal-infos .`"
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;sdk:dev;packages:trpc_client;commands:format-analyze_0"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted;sdk:dev;packages:trpc_client
            os:ubuntu-latest;pub-cache-hosted;sdk:dev
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@0a8a0fc875eb934c15d08629302413c671d3f672
        with:
          sdk: dev
      - id: checkout
        name: Checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
      - id: trpc_client_pub_upgrade
        name: trpc_client; dart pub upgrade
        run: dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: trpc_client
      - name: "trpc_client; dart format --output=none --set-exit-if-changed ."
        run: "dart format --output=none --set-exit-if-changed ."
        if: "always() && steps.trpc_client_pub_upgrade.conclusion == 'success'"
        working-directory: trpc_client
      - name: "trpc_client; dart analyze --fatal-infos ."
        run: dart analyze --fatal-infos .
        if: "always() && steps.trpc_client_pub_upgrade.conclusion == 'success'"
        working-directory: trpc_client
  job_004:
    name: "analyze_format; linux; Dart dev; PKG: trpc_generator; `dart format --output=none --set-exit-if-changed .`, `dart analyze --fatal-infos .`"
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;sdk:dev;packages:trpc_generator;commands:format-analyze_0"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted;sdk:dev;packages:trpc_generator
            os:ubuntu-latest;pub-cache-hosted;sdk:dev
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@0a8a0fc875eb934c15d08629302413c671d3f672
        with:
          sdk: dev
      - id: checkout
        name: Checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
      - id: trpc_generator_pub_upgrade
        name: trpc_generator; dart pub upgrade
        run: dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: trpc_generator
      - name: "trpc_generator; dart format --output=none --set-exit-if-changed ."
        run: "dart format --output=none --set-exit-if-changed ."
        if: "always() && steps.trpc_generator_pub_upgrade.conclusion == 'success'"
        working-directory: trpc_generator
      - name: "trpc_generator; dart analyze --fatal-infos ."
        run: dart analyze --fatal-infos .
        if: "always() && steps.trpc_generator_pub_upgrade.conclusion == 'success'"
        working-directory: trpc_generator
  job_005:
    name: "unit_test; linux; Dart 3.4.0; PKG: trpc_client; `dart test`"
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;sdk:3.4.0;packages:trpc_client;commands:test"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted;sdk:3.4.0;packages:trpc_client
            os:ubuntu-latest;pub-cache-hosted;sdk:3.4.0
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@0a8a0fc875eb934c15d08629302413c671d3f672
        with:
          sdk: "3.4.0"
      - id: checkout
        name: Checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
      - id: trpc_client_pub_upgrade
        name: trpc_client; dart pub upgrade
        run: dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: trpc_client
      - name: trpc_client; dart test
        run: dart test
        if: "always() && steps.trpc_client_pub_upgrade.conclusion == 'success'"
        working-directory: trpc_client
    needs:
      - job_001
      - job_002
      - job_003
      - job_004
  job_006:
    name: "unit_test; linux; Dart 3.4.0; PKG: trpc_generator; `dart test`"
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;sdk:3.4.0;packages:trpc_generator;commands:test"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted;sdk:3.4.0;packages:trpc_generator
            os:ubuntu-latest;pub-cache-hosted;sdk:3.4.0
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@0a8a0fc875eb934c15d08629302413c671d3f672
        with:
          sdk: "3.4.0"
      - id: checkout
        name: Checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
      - id: trpc_generator_pub_upgrade
        name: trpc_generator; dart pub upgrade
        run: dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: trpc_generator
      - name: trpc_generator; dart test
        run: dart test
        if: "always() && steps.trpc_generator_pub_upgrade.conclusion == 'success'"
        working-directory: trpc_generator
    needs:
      - job_001
      - job_002
      - job_003
      - job_004
  job_007:
    name: "unit_test; linux; Dart dev; PKG: trpc_client; `dart test`"
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;sdk:dev;packages:trpc_client;commands:test"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted;sdk:dev;packages:trpc_client
            os:ubuntu-latest;pub-cache-hosted;sdk:dev
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@0a8a0fc875eb934c15d08629302413c671d3f672
        with:
          sdk: dev
      - id: checkout
        name: Checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
      - id: trpc_client_pub_upgrade
        name: trpc_client; dart pub upgrade
        run: dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: trpc_client
      - name: trpc_client; dart test
        run: dart test
        if: "always() && steps.trpc_client_pub_upgrade.conclusion == 'success'"
        working-directory: trpc_client
    needs:
      - job_001
      - job_002
      - job_003
      - job_004
  job_008:
    name: "unit_test; linux; Dart dev; PKG: trpc_generator; `dart test`"
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;sdk:dev;packages:trpc_generator;commands:test"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted;sdk:dev;packages:trpc_generator
            os:ubuntu-latest;pub-cache-hosted;sdk:dev
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@0a8a0fc875eb934c15d08629302413c671d3f672
        with:
          sdk: dev
      - id: checkout
        name: Checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
      - id: trpc_generator_pub_upgrade
        name: trpc_generator; dart pub upgrade
        run: dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: trpc_generator
      - name: trpc_generator; dart test
        run: dart test
        if: "always() && steps.trpc_generator_pub_upgrade.conclusion == 'success'"
        working-directory: trpc_generator
    needs:
      - job_001
      - job_002
      - job_003
      - job_004
  job_009:
    name: "unit_test; windows; Dart 3.4.0; PKG: trpc_client; `dart test`"
    runs-on: windows-latest
    steps:
      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@0a8a0fc875eb934c15d08629302413c671d3f672
        with:
          sdk: "3.4.0"
      - id: checkout
        name: Checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
      - id: trpc_client_pub_upgrade
        name: trpc_client; dart pub upgrade
        run: dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: trpc_client
      - name: trpc_client; dart test
        run: dart test
        if: "always() && steps.trpc_client_pub_upgrade.conclusion == 'success'"
        working-directory: trpc_client
    needs:
      - job_001
      - job_002
      - job_003
      - job_004
  job_010:
    name: "unit_test; windows; Dart 3.4.0; PKG: trpc_generator; `dart test`"
    runs-on: windows-latest
    steps:
      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@0a8a0fc875eb934c15d08629302413c671d3f672
        with:
          sdk: "3.4.0"
      - id: checkout
        name: Checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
      - id: trpc_generator_pub_upgrade
        name: trpc_generator; dart pub upgrade
        run: dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: trpc_generator
      - name: trpc_generator; dart test
        run: dart test
        if: "always() && steps.trpc_generator_pub_upgrade.conclusion == 'success'"
        working-directory: trpc_generator
    needs:
      - job_001
      - job_002
      - job_003
      - job_004
  job_011:
    name: "unit_test; windows; Dart dev; PKG: trpc_client; `dart test`"
    runs-on: windows-latest
    steps:
      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@0a8a0fc875eb934c15d08629302413c671d3f672
        with:
          sdk: dev
      - id: checkout
        name: Checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
      - id: trpc_client_pub_upgrade
        name: trpc_client; dart pub upgrade
        run: dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: trpc_client
      - name: trpc_client; dart test
        run: dart test
        if: "always() && steps.trpc_client_pub_upgrade.conclusion == 'success'"
        working-directory: trpc_client
    needs:
      - job_001
      - job_002
      - job_003
      - job_004
  job_012:
    name: "unit_test; windows; Dart dev; PKG: trpc_generator; `dart test`"
    runs-on: windows-latest
    steps:
      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@0a8a0fc875eb934c15d08629302413c671d3f672
        with:
          sdk: dev
      - id: checkout
        name: Checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
      - id: trpc_generator_pub_upgrade
        name: trpc_generator; dart pub upgrade
        run: dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: trpc_generator
      - name: trpc_generator; dart test
        run: dart test
        if: "always() && steps.trpc_generator_pub_upgrade.conclusion == 'success'"
        working-directory: trpc_generator
    needs:
      - job_001
      - job_002
      - job_003
      - job_004
